SELECT * FROM NOTICE_VIEW

SELECT CODE, TITLE, WRITER, CONTENT, REGDATE, HIT, CMTCNT
FROM
	NOTICE N OUTER LEFT JOIN COMMENT C
	ON N.CODE = C.NOTICE_CODE
	GROUP CODE, TITLE, WRITER, CONTENT, REGDATE, HIT
	
SELECT NVL(MAX(TO_NUMBER(CODE)), 0) FROM NOTICE
SELECT * FROM NOTICE